[workspace]
resolver = "2"
members = [
    "crates/customtale-auth",
    "crates/customtale-protocol",
    "crates/customtale-server",
]

[workspace.dependencies]
customtale-protocol = { path = "crates/customtale-protocol" }
